package cardboard.util

import androidx.compose.runtime.Composable

expect class NativeMediaPlayer

enum class MediaPlayerState { IDLE, LOADING, PLAYING, PAUSED, STOPPED, DESTROYED }

/**
 * A media players that can load, play, pause, and stop media content.
 */
interface MediaPlayer {
    /**
     * Loads the media content from the specified URL. The URL can be a remote
     * URL or a local file path generated by getAssetURL(). This function
     * returns immediately after starting the loading process and does not wait
     * for the media to be fully loaded. Loading a media item does not start
     * playback immediately; you must call play() to start the playback after
     * loading.
     */
    fun load(url: String, repeat: Boolean = true)

    /**
     * Starts playback of the loaded media content. If the media is not loaded,
     * this function will cause it to start playing as soon as it is ready.
     */
    fun play()

    /**
     * Pauses the playback of the media content. If the media is not currently
     * playing, this function has no effect.
     */
    fun pause()

    /**
     * Stops the playback of the media content and resets the playback position
     * to the beginning. If the media is currently paused, this function simply
     * rewinds the media to the start. If the media is not loaded at all, this
     * function has no effect.
     */
    fun stop()

    /**
     * Destroy the underlying media player and release resources. Typically
     * after this the media player will no longer be usable.
     */
    fun destroy()

    /**
     * Runs the specified action when the media playback ends. This will be
     * called when the media reaches the end of playback, either because it
     * has finished playing or because it has been stopped. If the media is
     * repeating, this action will not be called unless stopped. Passing null
     * will remove any previously set action.
     */
    fun runWhenMediaEnds(action: (() -> Unit)?)

    /** The current state of the media player. */
    val state: MediaPlayerState

    /** The volume of the media player from 0.0 (muted) to 1.0 (full). */
    var volume: Float

    /** The native media player instance used for playback. */
    val native: NativeMediaPlayer
}

@Composable
expect fun rememberMediaPlayer(): MediaPlayer
