package cardboard

import cardboard.sdk.DistortionRenderer
import cardboard.sdk.DistortionRendererTarget
import cardboard.sdk.Eye
import cardboard.util.Matrix
import cardboard.util.NativeMediaPlayer

import okio.Source

enum class Engine { GLES2, GLES3, METAL, VULKAN }

/**
 * Creates the default native renderer for the Cardboard VR framework. The
 * default renderer provides a basic implementation. It uses a single render
 * texture for both eyes (which includes a depth buffer). It is suitable for
 * many applications.
 *
 * On Android it will use OpenGL ES 2.0 or 3.0 depending on the current GL
 * context capabilities during init(). On iOS it will use Metal.
 */
expect fun createDefaultNativeRenderer(): NativeRenderer

/**
 * Interface for a native renderer in the Cardboard VR framework. The native
 * renderer used by the Cardboard VR framework, responsible for rendering the
 * scene to the display using a given shader. Different platforms will have
 * different implementations of this interface, such as OpenGL ES on Android
 * and Metal on iOS. Custom implementations can be created to provide
 * additional functionality or to use different rendering techniques.
 *
 * All functions are expected to be called on the graphics thread and may not
 * work correctly if called on the main or any other thread.
 */
interface NativeRenderer {
    /**
     * The engine used by the renderer.
     */
    val engine: Engine

    /**
     * Initializes the renderer. This is called once when first displaying the renderer.
     * This should complete things like compiling shaders.
     */
    fun init(cr: CardboardRenderer, shader: Shader) { }

    /**
     * Destroys the renderer. This is called when the renderer is no longer needed.
     * This should clean up any resources allocated by the renderer.
     */
    fun destroy(cr: CardboardRenderer) { }

    /**
     * Setup the graphics for the renderer. This is called when the renderer is
     * first initialized or when the device/screen parameters change. This is
     * where you should set up textures and rendering resources. If they are
     * already set up, they old resources should be destroyed and new ones
     * created as appropriate. This must call cr.setTexture(). This returns a
     * DistortionRenderer that is used to render the scene.
     */
    fun setupGraphics(cr: CardboardRenderer): DistortionRenderer

    /**
     * Loads a texture mesh from the given indices, vertices, and uvs.
     */
    fun loadMesh(mesh: Mesh): NativeMesh

    /**
     * Loads a texture from the given URL to an image file. The URL can be a
     * remote URL or a local file path generated by getAssetURL(). By default,
     * the texture is flipped vertically to match the standard texture
     * coordinate system, but passing `flip = false` will load it without
     * flipping.
     */
    fun loadTexture(url: String, flip: Boolean = true): NativeTexture

    /**
     * Loads a texture from the given source data containing an image file
     * and not just raw pixel data (e.g. a PNG file). By default, the texture
     * is flipped vertically to match the standard texture coordinate system,
     * but passing `flip = false` will load it without flipping.
     */
    fun loadTexture(image: Source, flip: Boolean = true): NativeTexture

    /**
     * Loads a texture from the given byte array. The byte array must contain
     * the raw pixel data of the texture in either RGB or RGBA format
     * (depending on the `alpha` parameter).
     *
     * Note: on iOS, the alpha parameter must be true.
     */
    fun loadTexture(image: ByteArray, width: Int, height: Int, alpha: Boolean): NativeTexture

    /**
     * Loads a video texture from the given MediaPlayer. The MediaPlayer must
     * be prepared and ready to play the video. The texture will be updated
     * with the current video frame when the renderer is prepared to draw.
     *
     * The media player is a platform-specific object that handles video
     * playback. The caller is responsible for managing the lifecycle of the
     * player, including preparing it, releasing it when no longer needed,
     * adjusting volume, pausing and resuming playback when the app is not
     * active, and making sure it is looping if desired.
     */
    fun loadVideoTexture(player: NativeMediaPlayer): NativeTexture

    /**
     * Prepares the renderer to draw. This is called for each frame but before
     * any drawing is done.
     */
    fun prepareToDraw()

    /**
     * Prepares the renderer to draw for a specific eye. This is called for each
     * eye before drawing the scene for that eye.
     * @param eye The eye to prepare for (LEFT or RIGHT).
     */
    fun prepareToDraw(eye: Eye) { }

    /**
     * Prepares the renderer to draw the final distorted scene to the display.
     * Returns a DistortionRendererTarget that is used to render it.
     */
    fun prepareToDrawFinal(): DistortionRendererTarget

    /**
     * Reset the renderer before the next draw.
     */
    fun endDraw() { }

    /**
     * Set the model-view matrix for the renderer.
     */
    fun setModelViewMatrix(matrix: Matrix)
}

interface NativeMesh {
    fun draw()
    fun destroy()
}

interface NativeTexture {
    fun bind()
    fun destroy()
}
